AllCops:
  TargetRubyVersion: 2.5

# These non-default settings best reflect our current code style.
Layout/LineLength:
  Max: 80
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/AndOr:
  EnforcedStyle: always
Style/StderrPuts:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: true
  EnforcedStyle: squiggly
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: symmetrical
Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
Layout/SpaceInsideParens:
  EnforcedStyle: no_space
Layout/SpaceInsideReferenceBrackets:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space
Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline
Style/BarePercentLiterals:
  EnforcedStyle: percent_q
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods: [
     # Ruby keywords:
     gem, require, raise, cattr_accessor,
     # Test keywords:
     step, to, to_not, not_to,
     # GLI keywords
     desc, command, flag, arg_name, switch
     ]

# Either style of these arguably has its place depending on the context.
Style/FormatStringToken:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
  # However, these score at comparatively fewer offences, so I'll 
  # leave it here in case we want to enforce a style after all.
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

# The default configuration of these makes it hard to use proportional fonts.
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/SpaceAroundOperators:
  AllowForAlignment: false
Layout/SpaceBeforeFirstArg:
  AllowForAlignment: false

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
