/*
 * Conjur
 * This is an API definition for CyberArk Conjur OSS. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.conjur.sdk.endpoint;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.*;
import org.conjur.sdk.*;
import org.conjur.sdk.endpoint.*;
import org.conjur.sdk.model.*;
import org.junit.*;


/**
 * API tests for PublicKeysApi.
 */
public class PublicKeysApiTest extends ConfiguredTest {

    private final PublicKeysApi api = new PublicKeysApi();
    private final Pattern sshKeyPattern = Pattern.compile("ssh-rsa \\S+ \\S+\n");

    /**
     * Shows all public keys for a resource.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showPublicKeysTest() throws ApiException {
        String kind = "user";
        String identifier = "alice";
        ApiResponse<String> response = api.showPublicKeysWithHttpInfo(account, kind, identifier);

        Assert.assertEquals(200, response.getStatusCode());
        Matcher m = sshKeyPattern.matcher(response.getData());
        Assert.assertTrue(m.matches());
    }
}
