#!/bin/sh

# Log message
echo "Login as admin with user $KC_BOOTSTRAP_ADMIN_USERNAME"

# Authenticate with Keycloak
bin/kcadm.sh config credentials \
  --server http://localhost:8080 \
  --realm master \
  --user "$KC_BOOTSTRAP_ADMIN_USERNAME" \
  --password "$KC_BOOTSTRAP_ADMIN_PASSWORD"

# Log message for create user
echo "Creating user $1 with email $3"

# Create the User
bin/kcadm.sh create users \
  -r master \
  -s username="$1" \
  -s email="$3" \
  -s enabled=true

# Set the password for the User
echo "Setting password of user $1 to $2"
bin/kcadm.sh set-password \
  -r master \
  --username "$1" \
  -p "$2"
