apiPackage: com.cyberark.conjur.sdk.endpoint
modelPackage: com.cyberark.conjur.sdk.model
scmUrl: https://github.com/cyberark/conjur-sdk-java
invokerPackage: com.cyberark.conjur.sdk
artifactId: conjur-sdk-java
artifactDescription: Java Conjur SDK
hideGenerationTimestamp: true
licenseName: Apache 2.0
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
