/*
 * Conjur
 * This is an API definition for CyberArk Conjur OSS. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.1.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.conjur.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InfoAuthenticators
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-04T13:53:34.213Z[GMT]")
public class InfoAuthenticators {
  public static final String SERIALIZED_NAME_INSTALLED = "installed";
  @SerializedName(SERIALIZED_NAME_INSTALLED)
  private List<String> installed = null;

  public static final String SERIALIZED_NAME_CONFIGURED = "configured";
  @SerializedName(SERIALIZED_NAME_CONFIGURED)
  private List<String> configured = null;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private List<String> enabled = null;


  public InfoAuthenticators installed(List<String> installed) {
    
    this.installed = installed;
    return this;
  }

  public InfoAuthenticators addInstalledItem(String installedItem) {
    if (this.installed == null) {
      this.installed = new ArrayList<String>();
    }
    this.installed.add(installedItem);
    return this;
  }

   /**
   * Get installed
   * @return installed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getInstalled() {
    return installed;
  }


  public void setInstalled(List<String> installed) {
    this.installed = installed;
  }


  public InfoAuthenticators configured(List<String> configured) {
    
    this.configured = configured;
    return this;
  }

  public InfoAuthenticators addConfiguredItem(String configuredItem) {
    if (this.configured == null) {
      this.configured = new ArrayList<String>();
    }
    this.configured.add(configuredItem);
    return this;
  }

   /**
   * Get configured
   * @return configured
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getConfigured() {
    return configured;
  }


  public void setConfigured(List<String> configured) {
    this.configured = configured;
  }


  public InfoAuthenticators enabled(List<String> enabled) {
    
    this.enabled = enabled;
    return this;
  }

  public InfoAuthenticators addEnabledItem(String enabledItem) {
    if (this.enabled == null) {
      this.enabled = new ArrayList<String>();
    }
    this.enabled.add(enabledItem);
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getEnabled() {
    return enabled;
  }


  public void setEnabled(List<String> enabled) {
    this.enabled = enabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfoAuthenticators infoAuthenticators = (InfoAuthenticators) o;
    return Objects.equals(this.installed, infoAuthenticators.installed) &&
        Objects.equals(this.configured, infoAuthenticators.configured) &&
        Objects.equals(this.enabled, infoAuthenticators.enabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(installed, configured, enabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfoAuthenticators {\n");
    sb.append("    installed: ").append(toIndentedString(installed)).append("\n");
    sb.append("    configured: ").append(toIndentedString(configured)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

